#!/bin/bash

if [ -z $1 ]; then
    TARGET="tests/pdf_invalid.pdf"
else
    TARGET=$1
fi

PIN_ROOT=$(find .. -maxdepth 1 -type d -regextype sed -regex ".*pin.*" -print -quit)
$PIN_ROOT/pin -t obj-intel64/grtrace.so -- /usr/bin/gs -o nul -sDEVICE=nullpage $TARGET
